name: Deploy Blog

on:
  push:
    branches: [main]
    paths:
      - 'blogs/**'

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: blogs

      - name: Build Jekyll site
        run: |
          cd blogs
          bundle exec jekyll build --destination ../_site_blogs

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site_blogs
          destination_dir: blogs
